name: hobbyist
description: Hobbyist - Track your hobbies with discipline and motivation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/completion.wav
    - assets/splash_screen_full.png

flutter_native_splash:
  color: "#1b162a"
  image: assets/splash_screen_full.png
  android: true
  ios: true
  android_12:
    color: "#1b162a"
    image: assets/splash_screen_full.png
