name: hobbyist
description: Hobbyist - Track your hobbies with discipline and motivation
publish_to: 'none'
version: 1.0.0+30

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  audioplayers: ^5.2.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  firebase_performance: ^0.10.0+5
  firebase_remote_config: ^5.1.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.2.0
  in_app_review: 2.0.10
  url_launcher: ^6.3.1
  meta: ^1.9.0
  home_widget: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_core_platform_interface: ^5.0.0
  flutter_native_splash: ^2.3.10
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/completion.wav
    - assets/splash_screen_full.png

flutter_native_splash:
  color: "#1b162a"
  image: assets/splash_screen_full.png
  android: true
  ios: true
  android_12:
    color: "#1b162a"
    image: assets/splash_screen_full.png
